version: "3.8"

x-defaults: &defaults
  # Overrides default command so things don't shut down after the process ends.
  command: /bin/sh -c "while sleep 1000; do :; done"

services:
  java:
    <<: *defaults
    image: frison/dev:java
    environment:
      - MAVEN_OPTS=-Dmaven.repo.local=/workspace/.m2
      - JAVA_OPTS="-Xms512m -Xmx1024m"
    working_dir: /workspace/Wordstats
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/human/.ssh:ro